# Generated by Django 5.0.14 on 2026-04-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ProductoID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('PrecioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StockActual', models.IntegerField(default=0)),
                ('Activo', models.BooleanField(default=True)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Productos',
                'permissions': [('gestionar_inventario', 'Puede agregar, editar y ver inventario')],
            },
        ),
    ]
