# Generated by Django 5.0.14 on 2026-04-17 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('CategoriaID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'db_table': 'CategoriaProductos',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='StockActual',
        ),
        migrations.AddField(
            model_name='producto',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='TieneVariantes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='Categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoriaproducto'),
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('VarianteID', models.AutoField(primary_key=True, serialize=False)),
                ('Talla', models.CharField(blank=True, max_length=50, null=True)),
                ('Color', models.CharField(blank=True, max_length=50, null=True)),
                ('StockActual', models.IntegerField(default=0)),
                ('Activo', models.BooleanField(default=True)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
                'db_table': 'VarianteProductos',
            },
        ),
    ]
