# Generated by Django 5.0.14 on 2026-04-17 21:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categoriaproducto_remove_producto_stockactual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('CompraID', models.AutoField(primary_key=True, serialize=False)),
                ('NoFactura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Factura Física')),
                ('FechaCompra', models.DateTimeField(default=django.utils.timezone.now)),
                ('Total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Estado', models.CharField(choices=[('Completada', 'Completada'), ('Anulada', 'Anulada')], default='Completada', max_length=20)),
                ('Observaciones', models.TextField(blank=True, null=True)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ProveedorID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('Direccion', models.TextField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Activo', models.BooleanField(default=True)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('DetalleID', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('PrecioCosto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.compra')),
                ('VarianteProducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
                'db_table': 'DetallesCompra',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='Proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor'),
        ),
    ]
