# Generated by Django 5.0.14 on 2026-04-24 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha de Contratación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=100, verbose_name='Nombre del documento')),
                ('archivo', models.FileField(upload_to='documentos_docentes/', verbose_name='Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='docentes.docente')),
            ],
            options={
                'verbose_name': 'Documento del Docente',
                'verbose_name_plural': 'Documentos de Docentes',
            },
        ),
        migrations.CreateModel(
            name='CargaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_lectivo', models.IntegerField(default=2025, verbose_name='Año Lectivo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.materias', verbose_name='Materia')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.nivel', verbose_name='Nivel Académico')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.seccion', verbose_name='Sección / Grupo')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_academicas', to='docentes.docente')),
            ],
            options={
                'verbose_name': 'Carga Académica',
                'verbose_name_plural': 'Cargas Académicas',
                'unique_together': {('docente', 'nivel', 'materia', 'seccion', 'anio_lectivo')},
            },
        ),
    ]
