# Generated by Django 5.0.14 on 2026-01-29 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('numero_inss', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_contratacion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paga_inss', models.BooleanField(default=True)),
                ('paga_ir', models.BooleanField(default=True)),
                ('porcentaje_antiguedad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='recursos_humanos.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('salario_basico', models.DecimalField(decimal_places=2, max_digits=12)),
                ('horas_extras_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_antiguedad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_devengado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inss_laboral', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ir_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('otras_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.empleado')),
            ],
            options={
                'unique_together': {('empleado', 'mes', 'anio')},
            },
        ),
    ]
