# Generated by Django 5.0.14 on 2026-01-29 15:41

import recursos_humanos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to=recursos_humanos.models.path_documentos_empleado),
        ),
        migrations.AddField(
            model_name='empleado',
            name='diplomas',
            field=models.FileField(blank=True, null=True, upload_to=recursos_humanos.models.path_documentos_empleado),
        ),
    ]
