# Generated by Django 5.0.14 on 2026-01-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_empleado_curriculum_empleado_diplomas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroplanilla',
            name='horas_extras_cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='registroplanilla',
            name='horas_extras_valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
