# Generated by Django 5.0.14 on 2026-04-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0004_registroasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroplanilla',
            name='inatec',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='registroplanilla',
            name='inss_patronal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
