# Generated by Django 5.0.14 on 2026-04-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0005_registroplanilla_inatec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroplanilla',
            name='dias_trabajados',
            field=models.DecimalField(decimal_places=1, default=30.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='registroplanilla',
            name='tipo_periodo',
            field=models.CharField(choices=[('MENSUAL', 'Mensual Completo (30 Días)'), ('PRIMERA_QUINCENA', 'Primera Quincena (1-15)'), ('SEGUNDA_QUINCENA', 'Segunda Quincena (16-30)')], default='MENSUAL', max_length=20),
        ),
    ]
