# Generated by Django 5.0.14 on 2026-04-18 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0006_registroplanilla_dias_trabajados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('motivo', models.CharField(choices=[('RENUNCIA_INMEDIATA', 'Renuncia Inmediata (Art. 44)'), ('RENUNCIA_PREAVISO', 'Renuncia con Preaviso 15 días (Art. 45)'), ('DESPIDO_INJUSTIFICADO', 'Despido Injustificado (Art. 45)'), ('MUTUO_ACUERDO', 'Mutuo Acuerdo / Fin de Contrato')], max_length=30)),
                ('salario_base_calculo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aguinaldo_proporcional', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vacaciones_proporcionales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnizacion_antiguedad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_total_liquidado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.empleado')),
            ],
        ),
    ]
