# Generated by Django 5.0.14 on 2026-04-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0007_registroliquidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroliquidacion',
            name='contabilizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroplanilla',
            name='contabilizado',
            field=models.BooleanField(default=False),
        ),
    ]
