# Generated by Django 5.0.14 on 2026-04-24 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0008_registroliquidacion_contabilizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaFeriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('motivo', models.CharField(max_length=200)),
                ('es_nacional', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Día Feriado / No Laboral',
                'verbose_name_plural': 'Días Feriados / No Laborales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='minutos_tarde',
            field=models.IntegerField(default=0, help_text='Minutos de llegada después de la hora entrada + tolerancia'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='minutos_temprano',
            field=models.IntegerField(default=0, help_text='Minutos de salida antes de la hora de salida establecida'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Justificaciones o notas', null=True),
        ),
        migrations.CreateModel(
            name='HorarioEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_esperada', models.TimeField(default='08:00')),
                ('salida_esperada', models.TimeField(default='16:00')),
                ('minutos_tolerancia', models.IntegerField(default=15, help_text='Margen de gracia antes de marcar tardanza')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='recursos_humanos.empleado')),
            ],
        ),
    ]
