# Generated by Django 5.0.14 on 2026-04-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0009_diaferiado_registroasistencia_minutos_tarde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioempleado',
            name='es_flexible',
            field=models.BooleanField(default=False, help_text='Si es flexible, no se calculan tardanzas automáticas'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='multa_monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de castigo manual por tardanza o falta', max_digits=10),
        ),
    ]
