# Generated by Django 5.0.14 on 2026-04-24 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_activacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_caducidad', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidades',
            fields=[
                ('ModalidadID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreModalidad', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Modalidades',
                'db_table': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('NivelID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreNivel', models.CharField(max_length=255)),
                ('Activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Niveles',
                'db_table': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='Semestres',
            fields=[
                ('SemestreID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreSemestre', models.CharField(max_length=50)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Semestres',
                'db_table': 'Semestres',
            },
        ),
        migrations.CreateModel(
            name='TipoMatricula',
            fields=[
                ('TipoMatriculaID', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Matrícula',
                'db_table': 'TipoMatricula',
            },
        ),
        migrations.CreateModel(
            name='TServicio',
            fields=[
                ('TipoServicioID', models.AutoField(primary_key=True, serialize=False)),
                ('TipoServicio', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Servicio',
                'db_table': 'TServicio',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('TurnoID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreTurno', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Turnos',
                'db_table': 'Turno',
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('MateriaID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreMateria', models.CharField(max_length=50)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro')),
                ('activo', models.BooleanField(default=True)),
                ('NivelID', models.ForeignKey(db_column='NivelID', on_delete=django.db.models.deletion.CASCADE, to='configuracion.nivel')),
            ],
            options={
                'verbose_name_plural': 'Materias',
                'db_table': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('SeccionID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreSeccion', models.CharField(max_length=50)),
                ('CuposDisponibles', models.IntegerField()),
                ('Activo', models.BooleanField(default=True)),
                ('NivelID', models.ForeignKey(db_column='NivelID', on_delete=django.db.models.deletion.CASCADE, to='configuracion.nivel')),
            ],
            options={
                'verbose_name_plural': 'Secciones',
                'db_table': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='Cortes',
            fields=[
                ('CorteID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCorte', models.CharField(max_length=50)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('SemestreID', models.ForeignKey(db_column='SemestreID', on_delete=django.db.models.deletion.CASCADE, to='configuracion.semestres')),
            ],
            options={
                'verbose_name_plural': 'Cortes',
                'db_table': 'Cortes',
            },
        ),
        migrations.CreateModel(
            name='TiposCambio',
            fields=[
                ('TipoCambioID', models.AutoField(primary_key=True, serialize=False)),
                ('VigenciaInicio', models.DateField()),
                ('VigenciaFin', models.DateField()),
                ('CambioCompra', models.DecimalField(decimal_places=4, max_digits=10)),
                ('CambioVenta', models.DecimalField(decimal_places=4, max_digits=10)),
                ('MonedaOrigen', models.CharField(max_length=3)),
                ('MonedaDestino', models.CharField(max_length=3)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('UsuarioID', models.ForeignKey(db_column='UsuarioID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Cambio',
                'db_table': 'TiposCambio',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('ServicioID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreServicio', models.CharField(max_length=50)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Anio', models.IntegerField(db_column='Año')),
                ('FechaCreacion', models.DateTimeField(db_column='FechaCreacion')),
                ('Activo', models.BooleanField(default=True)),
                ('NivelID', models.ForeignKey(db_column='NivelID', on_delete=django.db.models.deletion.CASCADE, to='configuracion.nivel')),
                ('TipoServicioID', models.ForeignKey(db_column='TipoServicioID', on_delete=django.db.models.deletion.CASCADE, to='configuracion.tservicio')),
            ],
            options={
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicios',
            },
        ),
    ]
