# Generated by Django 5.0.14 on 2025-12-17 03:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_activacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_caducidad', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
