# Generated by Django 5.0.14 on 2025-09-07 05:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Matricula', '0001_initial'),
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arqueos',
            fields=[
                ('ArqueoID', models.AutoField(db_column='ArqueoID', primary_key=True, serialize=False)),
                ('FechaRegistro', models.DateTimeField(db_column='FechaRegistro')),
                ('Activa', models.BooleanField(db_column='Activa', default=True)),
                ('MontoDeclarado_Cordobas', models.DecimalField(db_column='MontoDeclarado_Cordobas', decimal_places=2, max_digits=10)),
                ('MontoDeclarado_USD', models.DecimalField(db_column='MontoDeclarado_USD', decimal_places=2, max_digits=10)),
                ('MontoCalculado_Cordobas', models.DecimalField(db_column='MontoCalculado_Cordobas', decimal_places=2, max_digits=10)),
                ('MontoCalculado_USD', models.DecimalField(db_column='MontoCalculado_USD', decimal_places=2, max_digits=10)),
                ('Diferencia_Cordobas', models.DecimalField(db_column='Diferencia_Cordobas', decimal_places=2, max_digits=10)),
                ('Diferencia_USD', models.DecimalField(db_column='Diferencia_USD', decimal_places=2, max_digits=10)),
                ('Fecha', models.DateField(db_column='Fecha')),
                ('Hora', models.TimeField(db_column='Hora')),
                ('Observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
            ],
            options={
                'verbose_name': 'Arqueo',
                'verbose_name_plural': 'Arqueos',
                'db_table': 'Arqueos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('FacturaID', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField(db_column='Fecha')),
                ('Total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=10)),
                ('MontoPagado', models.DecimalField(db_column='MontoPagado', decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('Saldo', models.DecimalField(db_column='Saldo', decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('Moneda', models.CharField(db_column='Moneda', max_length=3)),
                ('FechaRegistro', models.DateTimeField(db_column='FechaRegistro')),
                ('EsPorCuotas', models.BooleanField(db_column='EsPorCuotas')),
                ('Activa', models.BooleanField(db_column='Activa')),
                ('Estado', models.CharField(db_column='Estado', max_length=20)),
                ('Descuento', models.DecimalField(db_column='Descuento', decimal_places=2, max_digits=10)),
                ('DescuentoPorcentaje', models.DecimalField(db_column='DescuentoPorcentaje', decimal_places=2, max_digits=5)),
                ('EstudianteID', models.ForeignKey(db_column='EstudianteID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Matricula.estudiantes_nueva')),
                ('MatriculaID', models.ForeignKey(db_column='MatriculaID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Matricula.matricula')),
                ('TipoCambioID', models.ForeignKey(db_column='TipoCambioID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracion.tiposcambio')),
                ('UsuarioID', models.ForeignKey(db_column='UsuarioID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('ReciboID', models.AutoField(primary_key=True, serialize=False)),
                ('FechaPago', models.DateField(db_column='FechaPago')),
                ('MontoPagado', models.DecimalField(db_column='MontoPagado', decimal_places=2, max_digits=10)),
                ('Saldo', models.DecimalField(db_column='Saldo', decimal_places=2, max_digits=10)),
                ('Total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=10)),
                ('FechaRegistro', models.DateTimeField(db_column='FechaRegistro')),
                ('Estado', models.CharField(db_column='Estado', max_length=20)),
                ('FacturaID', models.ForeignKey(db_column='FacturaID', on_delete=django.db.models.deletion.CASCADE, to='facturacion.facturas')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'db_table': 'Recibo',
            },
        ),
        migrations.CreateModel(
            name='DetallesArqueo',
            fields=[
                ('DetalleArqueoID', models.AutoField(db_column='DetalleArqueoID', primary_key=True, serialize=False)),
                ('FacturaID', models.IntegerField(blank=True, db_column='FacturaID', null=True)),
                ('Monto', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=10)),
                ('Anulada', models.BooleanField(db_column='Anulada', default=False)),
                ('FechaRegistro', models.DateTimeField(db_column='FechaRegistro')),
                ('Activa', models.BooleanField(db_column='Activa', default=True)),
                ('MontoCordobas', models.DecimalField(blank=True, db_column='MontoCordobas', decimal_places=2, max_digits=10, null=True)),
                ('MontoUSD', models.DecimalField(blank=True, db_column='MontoUSD', decimal_places=2, max_digits=10, null=True)),
                ('TipoPago', models.CharField(db_column='TipoPago', max_length=10)),
                ('Fecha', models.DateField(db_column='Fecha')),
                ('ArqueoID', models.ForeignKey(db_column='ArqueoID', on_delete=django.db.models.deletion.CASCADE, to='facturacion.arqueos')),
                ('ServicioID', models.ForeignKey(blank=True, db_column='ServicioID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracion.servicios')),
                ('ReciboID', models.ForeignKey(blank=True, db_column='ReciboID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.recibo')),
            ],
            options={
                'verbose_name': 'DetallesArqueo',
                'verbose_name_plural': 'DetallesArqueos',
                'db_table': 'DetallesArqueo',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('DetalleID', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(db_column='Cantidad')),
                ('PrecioUnitario', models.DecimalField(db_column='PrecioUnitario', decimal_places=2, max_digits=10)),
                ('Subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, max_digits=10)),
                ('FechaRegistro', models.DateTimeField(db_column='FechaRegistro')),
                ('Activa', models.BooleanField(db_column='Activa')),
                ('MontoPagado', models.DecimalField(blank=True, db_column='MontoPagado', decimal_places=2, max_digits=10, null=True)),
                ('Saldo', models.DecimalField(blank=True, db_column='Saldo', decimal_places=2, max_digits=10, null=True)),
                ('Descuento', models.DecimalField(db_column='Descuento', decimal_places=2, max_digits=10)),
                ('DescuentoPorcentaje', models.DecimalField(db_column='DescuentoPorcentaje', decimal_places=2, max_digits=5)),
                ('ServicioID', models.ForeignKey(db_column='ServicioID', on_delete=django.db.models.deletion.PROTECT, to='configuracion.servicios')),
                ('FacturaID', models.ForeignKey(db_column='FacturaID', on_delete=django.db.models.deletion.CASCADE, to='facturacion.facturas')),
                ('ReciboID', models.ForeignKey(blank=True, db_column='ReciboID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.recibo')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
                'db_table': 'DetallesFactura',
            },
        ),
    ]
