# Generated by Django 5.0.14 on 2025-09-07 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arqueos',
            options={'managed': False, 'permissions': [('ver_arqueos', 'Puede ver e imprimir arqueos'), ('gestionar_arqueos', 'Puede abrir y cerrar un nuevo arqueo')], 'verbose_name': 'Arqueo', 'verbose_name_plural': 'Arqueos'},
        ),
        migrations.AlterModelOptions(
            name='facturas',
            options={'permissions': [('ver_facturas', 'Puede ver facturas, historial e información del estudiante'), ('crear_facturas', 'Puede crear nuevas facturas')], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='recibo',
            options={'permissions': [('ver_recibo', 'Puede ver los detalles del recibo e imprimir'), ('crear_recibo', 'Puede crear un nuevo recibo para un pago'), ('anular_recibo', 'Puede anular un recibo')], 'verbose_name': 'Recibo', 'verbose_name_plural': 'Recibos'},
        ),
    ]
