# Generated by Django 5.0.14 on 2026-04-17 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_licencia'),
        ('facturacion', '0002_alter_arqueos_options_alter_facturas_options_and_more'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='ProductoID',
            field=models.ForeignKey(blank=True, db_column='ProductoID', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='ServicioID',
            field=models.ForeignKey(blank=True, db_column='ServicioID', null=True, on_delete=django.db.models.deletion.PROTECT, to='configuracion.servicios'),
        ),
    ]
