# Generated by Django 5.0.14 on 2026-04-17 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_detallefactura_productoid_and_more'),
        ('inventario', '0002_categoriaproducto_remove_producto_stockactual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='ProductoID',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='VarianteProductoID',
            field=models.ForeignKey(blank=True, db_column='VarianteProductoID', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.varianteproducto'),
        ),
    ]
