# Generated by Django 5.0.14 on 2026-04-18 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_remove_detallefactura_productoid_and_more'),
        ('inventario', '0003_compra_proveedor_detallecompra_compra_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesarqueo',
            name='VarianteProductoID',
            field=models.ForeignKey(blank=True, db_column='VarianteProductoID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.varianteproducto'),
        ),
    ]
