# Generated by Django 5.0.14 on 2026-04-24 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes_Nueva',
            fields=[
                ('EstudianteID', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_MINED', models.CharField(blank=True, max_length=50, null=True)),
                ('NombreCompleto', models.CharField(max_length=100)),
                ('Genero', models.CharField(max_length=1)),
                ('FechaNacimiento', models.DateField()),
                ('Edad', models.IntegerField(blank=True, null=True)),
                ('Direccion', models.CharField(max_length=255)),
                ('NombreMadre', models.CharField(max_length=100)),
                ('CedulaMadre', models.CharField(blank=True, max_length=20, null=True)),
                ('TelefonoMadre', models.CharField(max_length=15)),
                ('OcupacionMadre', models.CharField(max_length=100)),
                ('NombrePadre', models.CharField(max_length=100)),
                ('CedulaPadre', models.CharField(blank=True, max_length=20, null=True)),
                ('TelefonoPadre', models.CharField(max_length=15)),
                ('OcupacionPadre', models.CharField(max_length=100)),
                ('NombreTutor', models.CharField(blank=True, max_length=100, null=True)),
                ('CedulaTutor', models.CharField(blank=True, max_length=20, null=True)),
                ('TelefonoTutor', models.CharField(blank=True, max_length=15, null=True)),
                ('OcupacionTutor', models.CharField(blank=True, max_length=100, null=True)),
                ('ResponsableEP', models.CharField(max_length=100)),
                ('FotoCarnet', models.ImageField(blank=True, null=True, upload_to='fotocarnet/')),
                ('ColegioProcedencia', models.CharField(blank=True, max_length=255, null=True)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('FechaRetiro', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('UsuarioID', models.ForeignKey(db_column='UsuarioID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'Estudiantes_Nueva',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('MatriculaID', models.AutoField(primary_key=True, serialize=False)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('FechaMatricula', models.DateField()),
                ('AñoMatricula', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('EstudianteID', models.ForeignKey(db_column='EstudianteID', on_delete=django.db.models.deletion.CASCADE, to='Matricula.estudiantes_nueva')),
                ('ModalidadID', models.ForeignKey(db_column='ModalidadID', on_delete=django.db.models.deletion.CASCADE, to='configuracion.modalidades')),
                ('NivelID', models.ForeignKey(db_column='NivelID', on_delete=django.db.models.deletion.CASCADE, to='configuracion.nivel')),
                ('SeccionID', models.ForeignKey(db_column='SeccionID', on_delete=django.db.models.deletion.CASCADE, to='configuracion.seccion')),
                ('TipoMatriculaID', models.ForeignKey(db_column='TipoMatriculaID', on_delete=django.db.models.deletion.CASCADE, to='configuracion.tipomatricula')),
                ('TurnoID', models.ForeignKey(db_column='TurnoID', on_delete=django.db.models.deletion.CASCADE, to='configuracion.turno')),
                ('UsuarioID', models.ForeignKey(db_column='UsuarioID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Matrículas',
                'db_table': 'Matricula',
            },
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('InscripcionID', models.AutoField(primary_key=True, serialize=False)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('AñoMatricula', models.IntegerField()),
                ('EstudianteID', models.ForeignKey(db_column='EstudianteID', on_delete=django.db.models.deletion.CASCADE, to='Matricula.estudiantes_nueva')),
                ('MateriaID', models.ForeignKey(db_column='MateriaID', on_delete=django.db.models.deletion.CASCADE, to='configuracion.materias')),
                ('ModalidadID', models.ForeignKey(db_column='ModalidadID', on_delete=django.db.models.deletion.CASCADE, to='configuracion.modalidades')),
                ('NivelID', models.ForeignKey(db_column='NivelID', on_delete=django.db.models.deletion.CASCADE, to='configuracion.nivel')),
                ('SeccionID', models.ForeignKey(db_column='SeccionID', on_delete=django.db.models.deletion.CASCADE, to='configuracion.seccion')),
                ('TurnoID', models.ForeignKey(db_column='TurnoID', on_delete=django.db.models.deletion.CASCADE, to='configuracion.turno')),
                ('MatriculaID', models.ForeignKey(db_column='MatriculaID', on_delete=django.db.models.deletion.CASCADE, to='Matricula.matricula')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('CalificacionID', models.AutoField(primary_key=True, serialize=False)),
                ('NotaCuantitativa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota (0.00 a 100.00)')),
                ('NotaCualitativa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comentario o Nota Cualitativa')),
                ('FechaRegistro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('AnioMatricula', models.IntegerField(db_column='AñoMatricula', default=2026, verbose_name='Año de Matrícula')),
                ('CorteID', models.ForeignKey(db_column='CorteID', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_m_corte', to='configuracion.cortes', verbose_name='Corte de Evaluación')),
                ('MateriaID', models.ForeignKey(db_column='MateriaID', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_m_materia', to='configuracion.materias', verbose_name='Materia')),
                ('SemestreID', models.ForeignKey(db_column='SemestreID', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_m_semestre', to='configuracion.semestres', verbose_name='Semestre')),
                ('InscripcionID', models.ForeignKey(db_column='InscripcionID', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_m_inscripcion', to='Matricula.inscripciones', verbose_name='Inscripción')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'Calificaciones',
                'unique_together': {('InscripcionID', 'CorteID')},
            },
        ),
    ]
