"""
Django settings for colegio_web project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4ezwg467r=gvg+d(7bs8j@iu@w2(06kdg6v887-jf@d0^!)r77'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['*']
#ALLOWED_HOSTS = ['172.168.0.107', 'MARCIO-ADM', '127.0.0.1']
ALLOWED_HOSTS = ['prueba.colegioshalom.win', 'localhost', '127.0.0.1', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'principal',
    'crispy_forms',
    'crispy_bootstrap5',
    'dashboard',
    'contabilidad',
    'configuracion',
    'Matricula',
    'reportes',
    'facturacion',
    'gestion_permisos',
    'docentes',
    'recursos_humanos',
    'core',
    'inventario',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.LicenciaMiddleware',
]

ROOT_URLCONF = 'colegio_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'inventario', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'colegio_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'ShalomDB_copia',
        'USER': 'Sa',
        'PASSWORD': 'Unpggl.2023!',
        'HOST': 'localhost\\SQLEXPRESS01',
        'PORT': '',
        
        
        'OPTIONS': {
        'driver': 'ODBC Driver 17 for SQL Server',
            
        }
    
        
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-ni'

TIME_ZONE = 'America/Managua'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
# Directorios para buscar archivos estáticos adicionales
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    
]

# Directorio donde se copiarán los archivos estáticos en producción
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5" # <--- Añade esta línea
CRISPY_TEMPLATE_PACK = "bootstrap5" # <--- Añade esta línea

# Configuraciones para la sesión de usuario
# Duración de la sesión en segundos. Por defecto es 1209600 (2 semanas).
SESSION_COOKIE_AGE = 86400  # Ejemplo: Sesión de 1 día (86400 segundos)

# Si es True, la sesión expira cuando el navegador se cierra.
# Si es False, la sesión dura lo que se especifica en SESSION_COOKIE_AGE.
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Compresión y almacenamiento para producción

# Debes poner la URL exacta de ngrok, empezando con https://
CSRF_TRUSTED_ORIGINS = ['https://prueba.colegioshalom.win']